### ISSUE TITLE
watchOS and tvOS via Carthage?

### ISSUE THREAD

**Issue by basememara** [onmyway133/Arcane#11]
I see #10 added `watchOS` support, but when I use Carthage it only build `macOS` and `iOS`.

Maybe because you have to add targets for them?

**Comment by onmyway133** [comment]
@basememara Hi, I will add the watchOS target for you

**Comment by onmyway133** [comment]
@basememara Hi, can you check https://github.com/onmyway133/Arcane/releases/tag/1.1.0?

**Comment by basememara** [comment]
Thank you for the promptness and the great library :)

This worked, but I made a few changes via PR #13.

Also, a few more related and unrelated suggestions to consider:

1. Add `tvOS` unit test target to match `iOS` and `macOS` testing coverage
2. Remove `Info.plist's` from unit tests
3. Remove `playgrounds` since makes the project a bit more crowded and doesn't add obvious benefits (can use unit tests instead)

**Comment by basememara** [comment]
..sorry piling up in this thread, but another suggestion: to convert to workspace and add the example app to it (make sure to remember not to "share" the scheme). That would make the playground less of a need as well.

**Comment by onmyway133** [comment]
@basememara Hi, I've updated to your suggestions: fixing Info.plist, adding tests for tvOS target. 

About the workspace, that is interesting, I will consider that. This was built using the template https://github.com/hyperoslo/SwiftPackage so that there is `Example` directory that contains all the demo, to see how it integrates well with Cocoapods.

Feel free to close the issue if it has fixed the problem for you 😉
