### ISSUE TITLE
Header '/usr/include/CommonCrypto/CommonCrypto.h' not found

### ISSUE THREAD

**Issue by fpg1503** [onmyway133/Arcane#4]
Whenever I try to compile a project using Arcane I get the following error on `CCommonCrypto/module.modulemap`:

> (...)/Pods/Arcane/Sources/CCommonCrypto/module.modulemap:2:10: Header '/usr/include/CommonCrypto/CommonCrypto.h' not found

I'm using it as a pod dependecy. What am I doing wrong?

**Comment by onmyway133** [comment]
@fpg1503 Hi, I don't get that problem. Can you run 

```
pod repo update
pod install
```

again with `pod 'Arcane', git: 'https://github.com/onmyway133/Arcane'` in your `Podfile`? 

Which iOS version are you running on?

**Comment by fpg1503** [comment]
I'm running on iOS 9.3. Since I'm using as a dependency so I have `s.dependecy 'Arcane` in my `.podspec`. It resolves to [this podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/Arcane/0.2.0/Arcane.podspec.json) (which points to the [`0.2.0` tag](https://github.com/onmyway133/Arcane/tree/0.2.0)). 

I've tried updating the repo, deintergrating and reinstalling the pod but it didn't help. I'm running on the iOS Simulator, can that be an issue?

**Comment by fpg1503** [comment]
Here's the pod for reference: https://github.com/fpg1503/sinesp-swift (I was checking all the licenses of all my dependencies before making it public)

**Comment by onmyway133** [comment]
@fpg1503 Hi, I run your project, although having problem with https://github.com/fpg1503/Regex.swift `[!] Unable to find a specification for`Regex.swift`depended upon by`sinesp``, but I see that I can build the project successfully, even on the simulator

I'm on `cocoapods 1.0.1`. Btw, this is another podspec that relies on Arcane https://github.com/hyperoslo/Flasker/blob/master/Flasker.podspec

![a](https://cloud.githubusercontent.com/assets/2284279/17870466/f274c7e6-68b7-11e6-9156-7c948d379ffb.png)

**Comment by fpg1503** [comment]
That's pretty weird, I'm also on `cocoapods 1.0.1`.
If you just cloned it and ran it you're using a modified version of your pod (I've [hardcoded the simulator CommonCrypto location](https://github.com/fpg1503/sinesp-swift/commit/59fb880e756ed0f103b94fbc8df9c1e89b8dfb85)).

I'll check what's going on with `Regex.swift` and what Flasker is doing that I'm not.

**Comment by onmyway133** [comment]
@fpg1503 Hi, I run `pod deintegrate` and `pod install` so that your modified code is cleared. I'm on Xcode 7.3.1

**Comment by fpg1503** [comment]
Yeah, I also run into this problem when running Flasker's Example and Arcane's example. I'm on
- Xcode 7.3.1 (7D1014)
- Mac OS X 10.11.6 (15G31)
- CocoaPods 1.0.1
- Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.31)

There's no `include` directory inside my `/usr/`.

**Comment by onmyway133** [comment]
@fpg1503 Do you see `CommonCrypto` inside `open /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include` ?

**Comment by fpg1503** [comment]
@onmyway133 Yes, I do

**Comment by fpg1503** [comment]
It's weird because it doesn't work on my machine but works on Travis

**Comment by onmyway133** [comment]
I read on SO that some people have problem with Xcode-beta, so just to double check that my `Xcode Command Line Tools is Xcode 7.3.1` and my `xcodeselect -p` is `/Applications/Xcode.app/Contents/Developer`

I just see that this https://github.com/stephencelis/SQLite.swift/blob/743530d1e56c86b5cd4df5153839a98ecb05bf5f/SQLite/module.modulemap uses `modulemap` approach too. Can you run their example successfully?

**Comment by fpg1503** [comment]
<img width="600" alt="screen shot 2016-08-22 at 6 24 25 pm" src="https://cloud.githubusercontent.com/assets/5491536/17872271/b1ccbaae-6895-11e6-9aa1-e927b52a8d0a.png">

> xcode-select -p
> /Applications/Xcode.app/Contents/Developer

Their example doesn't compile on `743530d` (old Swift version) and it the `modulemap` was removed on`master`.

It probably has something to do with my Xcode but I'm not really sure how to fix it/avoid that other people also have that issue.

**Comment by fpg1503** [comment]
Apparently they solved it by special casing for each platform: https://github.com/stephencelis/SQLite.swift/blob/master/SQLite.swift.podspec#L35

**Comment by cjwirth** [comment]
I don't really remember why I have the separate modulemaps in the SQLite.swift project, but IIRC, there was some Xcode update where you couldn't use the `/usr/include` headers, and had to use the `/Applications/Xcode.app/Contents/Developer/Platforms/...` headers. Then, because of that, you had to use the specific one for each platform you were building for. 

So I just made the settings point at the modulemaps that were pointing to the right headers.

**Comment by onmyway133** [comment]
@cjwirth many thanks. I give the credit in the PR
@fpg1503 Hi, I update https://github.com/onmyway133/Arcane/pull/5 and bump to `0.3.0`. Can you check if it works for you?

**Comment by fpg1503** [comment]
It works beautifully!!!
🎉🎉🎉🎉🎉🎉🎉
Thanks to all of you for the time, effort and dedication 😉

**Comment by wuf810** [comment]
Hey. I'm running Xcode 8.3.2. Trying to compile the example project and I'm getting this problem too. Has anything changed since you made this fix last August.

Any suggestions for a workaround?

**Comment by onmyway133** [comment]
@wuf810 Hey, I just run the demo again. It builds OK. Can you checkout the latest version from `mater`?

**Comment by iwasrobbed-ks** [comment]
@wuf810 @onmyway133 Since the paths are hard-coded, it might break if you have Xcode betas installed or it named something other than `Xcode.app` (e.g. see https://github.com/onmyway133/Arcane/pull/5/files#diff-fa0f25757a80e18600824be1e1ed0d14R2)

Better to create a run script that swaps that out with whatever the SDK root variable is

**Comment by wuf810** [comment]
Thanks. I don’t remember but very likely I had my XCode renamed so this makes sense. Thanks for the reply.
